swagger: '2.0'
info:
  version: 1.0.0
  title: VOLTTRONData
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  '/GeneralDatas/{id}':
    get:
      tags:
        - GeneralData
      summary: 'Find a model instance by {{id}}'
      operationId: GeneralData.findOne
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/GeneralData'
      deprecated: false
    put:
      tags:
        - GeneralData
      summary: Put attributes for a model instance and persist it
      operationId: GeneralData.replace
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: true
          schema:
            $ref: '#/definitions/GeneralData'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/GeneralData'
      deprecated: false
    patch:
      tags:
        - GeneralData
      summary: Patch attributes for a model instance and persist it
      operationId: GeneralData.update
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: true
          schema:
            $ref: '#/definitions/GeneralData'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/GeneralData'
      deprecated: false
    delete:
      tags:
        - GeneralData
      summary: 'Delete a model instance by {{id}}'
      operationId: GeneralData.delete
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
  /GeneralDatas:
    post:
      tags:
        - GeneralData
      summary: Create a new instance of the model and persist it
      operationId: GeneralData.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: true
          schema:
            $ref: '#/definitions/GeneralData'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/GeneralData'
      deprecated: false
    get:
      tags:
        - GeneralData
      summary: Find all instances of the model
      operationId: GeneralData.findAll
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/GeneralData'
      deprecated: false
    delete:
      tags:
        - GeneralData
      summary: Delete all instances of the model
      operationId: GeneralData.deleteAll
      responses:
        '200':
          description: Request was successful
      deprecated: false
definitions:
  GeneralData:
    properties:
      id:
        type: string
      PQEnabled:
        type: boolean
      VFEnabled:
        type: boolean
      QFEnabled:
        type: boolean
      PVEnabled:
        type: boolean
      onGrid:
        type: boolean
      offGrid:
        type: boolean
      realPwrSet:
        type: number
      reactPwrSet:
        type: number
      voltageSet:
        type: number
      freqSet:
        type: number
      time:
        type: number
    additionalProperties: false
    required:
      - PQEnabled
      - VFEnabled
      - QFEnabled
      - PVEnabled
      - onGrid
      - offGrid
      - realPwrSet
      - reactPwrSet
      - voltageSet
      - freqSet
      - time
